module.exports = {
  main_screen: {
    marginTop: 30,
    display: "flex",
    flexDirection: "column",
    backgroundColor: "white",
    width: "100%",
    height: "100%",
    alignItems: "center",
  },
  main_screen__display: {
    elevation: 10,
    width: "95%",
    backgroundColor: "#031a2a",
    borderRadius: 10,
    display: "flex",
    marginBottom: 10,
    padding: 10,
    marginTop: 10,
  },
  main_screen__display_text: {
    fontSize: 50,
    textAlign: "right",
    color: "white",
  },
  main_screen_keypad: {
    width: "100%",
    height: "75%",
    display: "flex",
  },
  main_screen_keypad_row: {
    display: "flex",
    flexDirection: "row",
    backgroundColor: "white",
    width: "100%",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 10,
  },
  btn_outer: {
    width: 70,
    height: 70,
    backgroundColor: "#ef7171",
    borderRadius: 90,
    elevation: 10,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
  },
  btn1_outer: {
    width: 70,
    height: 70,
    backgroundColor: "#031a2a",
    borderRadius: 90,
    elevation: 10,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
  },
  btn2_outer: {
    width: 70,
    height: 70,
    backgroundColor: "#efa82d",
    borderRadius: 90,
    elevation: 10,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
  },
  bg1_button: {
    color: "white",
    fontSize: 25,
    fontWeight: "bold",
  },
};
